# Generated by Django 5.2.14 on 2026-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان سند")),
                (
                    "file",
                    models.FileField(upload_to="docs/", verbose_name="فایل سند (docx)"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="متن کامل استخراج شده"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
            ],
            options={
                "verbose_name": "سند",
                "verbose_name_plural": "اسناد",
            },
        ),
        migrations.CreateModel(
            name="QAHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="پرسش کاربر")),
                ("answer", models.TextField(verbose_name="پاسخ هوش مصنوعی")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
            ],
            options={
                "verbose_name": "تاریخچه پرسش",
                "verbose_name_plural": "تاریخچه پرسش\u200cها",
            },
        ),
    ]
