# Generated by Django 5.2.14 on 2026-05-20 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to="docs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx", "pdf", "txt"]
                    )
                ],
                verbose_name="فایل سند",
            ),
        ),
    ]
