# Generated by Django 5.2.14 on 2026-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="qahistory",
            name="prompt",
            field=models.TextField(blank=True, null=True, verbose_name="پرامپت ارسالی"),
        ),
        migrations.AddField(
            model_name="qahistory",
            name="sources",
            field=models.JSONField(blank=True, null=True, verbose_name="اسناد منبع"),
        ),
    ]
